# #cloud-config
# hostname: ${hostname}
# manage_etc_hosts: true
# users:
#   - name: ubuntu
#     sudo: ALL=(ALL) NOPASSWD:ALL
#     groups: sudo
#     shell: /bin/bash
#     ssh_authorized_keys:
#       - YOUR_SSH_PUBLIC_KEY
# runcmd:
#   - apt update && apt upgrade -y
#   - apt install -y curl jq bash-completion
#   - echo "net.ipv4.ip_forward = 1" >> /etc/sysctl.conf
#   - sysctl -p
#   - echo "Cloud-init setup completed for master node"
#cloud-config
users:
  - name: ubuntu
    sudo: ALL=(ALL) NOPASSWD:ALL
    shell: /bin/bash
    ssh_authorized_keys:
      - ssh-rsa AAAAB3...your-ssh-public-key...
