all:
  hosts:
    master-1:
      ansible_host: 192.168.1.101
    master-2:
      ansible_host: 192.168.1.102
    master-3:
      ansible_host: 192.168.1.103
    worker-1:
      ansible_host: 192.168.1.104
    worker-2:
      ansible_host: 192.168.1.105
    worker-3:
      ansible_host: 192.168.1.106
    haproxy:
      ansible_host: 192.168.1.100

  children:
    masters:
      hosts:
        master-1:
        master-2:
        master-3:
    workers:
      hosts:
        worker-1:
        worker-2:
        worker-3:
    loadbalancer:
      hosts:
        haproxy:
