- name: Add Istio Helm repository
  kubernetes.core.helm_repository:
    name: istio
    repo_url: "https://istio-release.storage.googleapis.com/charts"

- name: Install Istio Base
  kubernetes.core.helm:
    name: istio-base
    chart_ref: istio/base
    release_namespace: istio-system
    create_namespace: true
    state: present

- name: Install Istio Control Plane
  kubernetes.core.helm:
    name: istiod
    chart_ref: istio/istiod
    release_namespace: istio-system
    state: present

- name: Install Istio Ingress Gateway
  kubernetes.core.helm:
    name: istio-ingress
    chart_ref: istio/gateway
    release_namespace: istio-system
    state: present
