- name: Install RKE2 on master nodes
  hosts: masters
  become: true
  tasks:
    - name: Download RKE2 install script
      shell: curl -sfL https://get.rke2.io | sh -

    - name: Enable and start RKE2 service
      systemd:
        name: rke2-server.service
        enabled: yes
        state: started

    - name: Copy kubeconfig to user home
      copy:
        src: /etc/rancher/rke2/rke2.yaml
        dest: /home/ubuntu/.kube/config
        remote_src: yes
        owner: ubuntu
        group: ubuntu
        mode: '0644'
